
- name: Create frontend network
  docker_network:
    name: frontend_network

- name: Making sure default install directory is created
  file:
    path: "{{ reternal.install_dir }}"
    state: directory

- name: Run frontend container
  docker_container:
    name: frontend
    image: "reternal/ui:{{ frontend.tag }}"
    state: started
    purge_networks: yes
    networks_cli_compatible: yes
    recreate: yes
    env:
      RT_API_BASE_URL: "{{ frontend.api_base_url }}"
      RT_OAUTH_AUTHORITY_URL: "{{ frontend.oauth_authority_url }}"
      RT_OAUTH_AUTHORIZE_URL: "{{ frontend.oauth_authorize_url }}"
      RT_OAUTH_CLIENT_ID: "{{ frontend.oauth_client_id }}"
      RT_OAUTH_REDIRECT_URL: "{{ frontend.oauth_redirect_url }}"
    networks:
      - name: frontend_network
        aliases:
          - frontend
    # volumes:
    #   - /opt/reternal/navigator.json:/usr/share/nginx/html/mitre-navigator/assets/config.json