- name: Run API container
  docker_container:
    name: apitasks
    image: "reternal/backend:{{ api.tag }}"
    state: started
    purge_networks: yes
    networks_cli_compatible: yes
    recreate: "{{ api.recreate | default('yes') }}"
    entrypoint: ["celery", "--app", "app.workers", "worker", "-Q", "api"]
    env:
      RT_CELERY_BACKEND: "{{ celery.backend }}"
      RT_MONGO_HOST: "mongodb"
      RT_REDIS_PATH_SOCKETIO: "{{ redis.path.socketio }}"
      RT_CELERY_BROKER: "{{ celery.broker }}"
      RT_REDIS_PATH_CACHE: "{{ redis.path.cache }}"
      RT_MONGO_USERNAME: "{{ mongodb.username }}"
      RT_MONGO_PASSWORD: "{{ vault.mongodb.password }}"
      RT_SERVICE_TOKEN: "{{ vault.api.service_token }}"
    networks:
      - name: backend_network
        aliases:
          - apitasks