- name: Install PyOpenSSL to generate self signed cert
  pip:
    name: pyOpenSSL

- name: Create proxy config directory
  file:
    path: "{{ proxy_target_dir }}"
    state: directory

- name: Create proxy config directory
  file:
    path: "{{ proxy_target_dir }}/tls"
    state: directory

- name: Generate private key
  openssl_privatekey:
    path: "{{ proxy_target_dir }}/tls/{{ item }}.key"
  with_list:
    - "{{ proxy.ui.domain }}"
    - "{{ proxy.c2.domain }}"

- name: Generate CSR 
  openssl_csr:
    path: "{{ proxy_target_dir }}/tls/{{ item }}.csr"
    privatekey_path: "{{ proxy_target_dir }}/tls/{{ item }}.key"
    common_name: "{{ item }}"
  with_list:
    - "{{ proxy.ui.domain }}"
    - "{{ proxy.c2.domain }}"

- name: Generate self signed certificate
  openssl_certificate:
    path: "{{ proxy_target_dir }}/tls/{{ item }}.crt"
    privatekey_path: "{{ proxy_target_dir }}/tls/{{ item }}.key"
    csr_path: "{{ proxy_target_dir }}/tls/{{ item }}.csr"
    provider: selfsigned
    subject_alt_name: "{{ item }}"
  with_list:
    - "{{ proxy.ui.domain }}"
    - "{{ proxy.c2.domain }}"
