
- name: Create frontend network
  docker_network:
    name: frontend_network

- name: Creating config directory
  file:
    path: "{{ reternal.install_dir }}/ui"
    state: directory

- name: Making sure default install directory is created
  file:
    path: "{{ reternal.install_dir }}"
    state: directory

- name: Archiving UI components
  archive:
    path: "../ui"
    dest: "../ui.tgz"
  delegate_to: localhost
  become: no

- name: Extract UI components to target
  unarchive:
    src: "../ui.tgz"
    dest: "{{ reternal.install_dir }}"

- name: Copy navigator template to target server
  template:
    src: navigator.json.j2
    dest: /opt/reternal/navigator.json

- name: Build ui container
  docker_image:
    name: reternal/ui
    path: "{{ reternal.install_dir }}/ui"
    buildargs:
      VUE_APP_BASEAPI: "{{ reternal.api_dest }}/api/v1"
      VUE_APP_SOCKETHOST: "{{ reternal.api_dest }}"
    force: yes

- name: Run UI container
  docker_container:
    name: reternal-ui
    image: reternal/ui
    state: started
    recreate: yes
    networks:
      - name: frontend_network
        aliases:
          - reternal-uis
    volumes:
      - /opt/reternal/navigator.json:/usr/share/nginx/html/mitre-navigator/assets/config.json
