
- include_vars: vault.yml

- name: Making sure default install directory is created
  file:
    path: "{{ reternal.install_dir }}"
    state: directory
  
- name: Archiving C2 components
  archive:
    path: "../c2"
    dest: "../c2.tgz"
  delegate_to: localhost
  become: no

- name: Extract C2 components to target
  unarchive:
    src: "../c2.tgz"
    dest: "{{ reternal.install_dir }}"

- name: Build C2 container
  docker_image:
    name: reternal/c2
    path: "{{ c2_target_dir }}"
    force: yes

- name: Run C2 container
  docker_container:
    name: reternal-c2
    image: reternal/c2
    state: started
    recreate: yes
    env:
      C2_SECRET: "{{ passwords.c2_secret }}"
    networks:
      - name: backend_network
        aliases:
          - reternal-c2
  
