- include_vars: vault.yml

- name: Making sure default install directory is created
  file:
    path: "{{ reternal.install_dir }}"
    state: directory
  
- name: Run C2 container
  docker_container:
    name: c2
    image: "reternal/c2:{{ c2.tag}}"
    state: started
    pull: "{{ c2.pull | default('yes') }}"
    recreate: "{{ c2.recreate | default('yes') }}"
    purge_networks: yes
    networks_cli_compatible: yes
    env:
      RT_CELERY_BACKEND: "{{ celery.backend }}"
      RT_CELERY_BROKER: "{{ celery.broker }}"
      RT_EMPIRE_PATH: "{{ c2.empire_path }}"
      RT_EMPIRE_PASSWORD: "{{ vault.empire2.password }}"
      RT_EMPIRE_USERNAME: "{{ empire2.username }}"
    networks:
      - name: backend_network
        aliases:
          - c2
