- name: Check if Ansible vault file exists
  stat: 
    path: "{{ vault_path }}"
  register: vault_object

- name: Create blank template file for ansible Vault
  template:
    src: vault.yml.j2
    dest: "{{ vault_path }}"
  when: vault_object.stat.exists == False

- name: Create Ansible vault
  command: ansible-vault encrypt {{ vault_path }}
  when: vault_object.stat.exists == False

