# This is the default settings file for the reternal playbook.
# None of the variables will have to be changed for testing. In it's current state the following will be deployed:

# API on https://<your_ip>:8443
# UI on https://<your_ip>:9443
# C2 Endpoint on https://<your_ip>:443

# A default firewall won't be enabled, so be carefull what you expose!

# PS. The certs role will create self-signed certificates. You can replace these with your own certs later on


reternal:
  install_dir: "{{ lookup('env','HOME') }}/opt/reternal" # Install location for source code
  api_dest: "https://{{ hostvars['rtn-dev-01']['ansible_default_ipv4']['address'] }}:8443" # IP/Domain used inside the UI to perform API calls
  c2_dest: "https://{{ hostvars['rtn-dev-01']['ansible_default_ipv4']['address'] }}/api/v1/ping" # Default endpoint used for our agent to get tasks
  cors: "*" # Change value to enforce CORS policy (ie. only allow API requests from IP/domain 'X')


ui:
  tag: dev

c2:
  tag: dev
  empire_path: "https://empire2:1337/api/"

search:
  tag: dev
  splunk_path: ""

celery:
  broker: "amqp://{{ rabbitmq.username }}:{{ vault.rabbitmq.password }}@rabbitmq:5672/{{ rabbitmq.vhost }}"
  backend: "redis://:{{ vault.redis.password }}@redis:6379/0"

empire2:
  tag: latest
  username: hello_there

api:
  tag: dev
  port: 5000
  host: "0.0.0.0"

  # Celery secrets/config


# # UI / Oauth config
# RT_API_BASE_URL=http://127.0.0.1:5000/api/v1
# RT_OAUTH_AUTHORITY_URL=https://login.microsoftonline.com/f97837ba-3ed6-4814-87b1-60cec14edb64/v2.0/
# RT_OAUTH_AUTHORIZE_URL=https://login.microsoftonline.com/f97837ba-3ed6-4814-87b1-60cec14edb64/v2.0/authorize
# RT_OAUTH_CLIENT_ID=7d8fa818-2178-4819-bb3a-9b551728add0
# RT_OAUTH_REDIRECT_URL=http://localhost:9090/login


redis:
  tag: latest

rabbitmq:
  tag: latest
  vhost: reternal
  username: reternal

mongodb:
  tag: latest
  root_username: reternalroot # Custom root username
  username: reternal # Username used for Mongo DB
  db: reternal # Default database for reternal


proxy: 
  c2: 
    container: "reternal-c2" # No need to change - container name for our C2 container, 
    domain: "{{ hostvars['rtn-dev-01']['ansible_default_ipv4']['address'] }}" #  CN for our self signed cert
    port: 443 # Port exposed by nginx that will forward requests to our C2 container

  ui:
    container: "reternal-ui" # No need to change - container name for our UI container, 
    domain: "{{ hostvars['rtn-dev-01']['ansible_default_ipv4']['address'] }}" # CN for our self signed cert
    port: 8443 # Port exposed by nginx that will forward requests to our UI container
  
  api:
    container: "reternal-api" # No need to change - container name for our API container, 
    domain: "{{ hostvars['rtn-dev-01']['ansible_default_ipv4']['address'] }}" # CN for our self signed cert
