- name: Making sure default install directory is created
  file:
    path: "{{ reternal.install_dir }}"
    state: directory
  
- name: Archiving Compiler components
  archive:
    path: "../agent"
    dest: "../agent.tgz"
  delegate_to: localhost
  become: no

- name: Extract Compiler components to target
  unarchive:
    src: "../agent.tgz"
    dest: "{{ reternal.install_dir }}"

- name: Build compiler container
  docker_image:
    name: reternal/compiler
    path: "{{ compiler_target_dir }}"
    force: yes

- name: Run compiler container
  docker_container:
    name: reternal-compiler
    image: reternal/compiler
    state: started
    recreate: yes
    networks:
      - name: backend_network
        aliases:
          - reternal-c2
