- include_vars: vault.yml

- name: Making sure default install directory is created
  file:
    path: "{{ reternal.install_dir }}"
    state: directory

- name: Archiving source CLI components
  archive:
    path: "../cli"
    dest: "../cli.tgz"
  delegate_to: localhost
  become: no

- name: Archiving source mapping components
  archive:
    path: "../mitre"
    dest: "../mitre.tgz"
  delegate_to: localhost
  become: no

- name: Extract source CLI to target
  unarchive:
    src: "../cli.tgz"
    dest: "{{ reternal.install_dir }}"

- name: Extract source mapping to target
  unarchive:
    src: "../mitre.tgz"
    dest: "{{ reternal.install_dir }}"

- name: Copy management script to target
  copy:
    src: ../manage.py
    dest: "{{ reternal.install_dir }}/"

- name: Installing required packages
  pip:
    name: ['mongoengine', 'oyaml', 'requests', 'pexpect']
