- include_vars: vault.yml

- name: Archiving source CLI components
  archive:
    path: "../cli"
    dest: "../cli.tgz"
  delegate_to: localhost
  become: no

- name: Archiving source mapping components
  archive:
    path: "../mitre"
    dest: "../mitre.tgz"
  delegate_to: localhost
  become: no

- name: Extract source CLI to target
  unarchive:
    src: "../cli.tgz"
    dest: "{{ extract_target_dir }}"

- name: Extract source mapping to target
  unarchive:
    src: "../mitre.tgz"
    dest: "{{ extract_target_dir }}"

- name: Copy management script to target
  copy:
    src: ../manage.py
    dest: "{{ reternal.install_dir }}/"

- name: Installing required packages
  pip:
    name: ['mongoengine', 'oyaml', 'requests', 'pexpect']

- name: Running configuration script for first time use
  expect: 
    command: "python3 {{ reternal.install_dir }}/manage.py -install create -t all"
    responses:
      (.*)Mongo Password(.*): "{{ passwords.mongo_reternal_pass }}"
      (.*)Username(.*): '{{ login_username }}'
      (.*)Password(.*): '{{ login_password }}'
      (.*)Role(.*): 'Admin'
  register: manage_script

- debug: msg="{{ manage_script.stdout }}"

