
- include_vars: vault.yml

- name: Create backend network
  docker_network:
    name: backend_network

- name: Create persistent DB volume
  docker_volume:
    name: mongodb-data

- name: Installing pymongo for DB management
  pip:
    name: pymongo
    state: present

- name: Run mongo container
  docker_container:
    name: mongodb
    image: mongo
    state: started
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ passwords.mongo_root_user }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ passwords.mongo_root_pass }}"
    networks:
      - name: backend_network
        aliases:
          - mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "127.0.0.1:27017:27017"

- name: Create mongodb user and pass for reternal
  mongodb_user:
    login_user: "{{ passwords.mongo_root_user }}"
    login_password: "{{ passwords.mongo_root_pass }}"
    database: "{{ database.db }}"
    user: "{{ database.user }}"
    password: "{{ passwords.mongo_reternal_pass }}"
    state: present
    roles: readWrite

- name: Run redis container
  docker_container:
    name: redis
    image: redis
    state: started
    networks:
      - name: backend_network
        aliases:
          - redis-service

- name: Making sure default install directory is created
  file:
    path: "{{ reternal.install_dir }}"
    state: directory

- name: Archiving backend components
  archive:
    path: "../backend"
    dest: "../backend.tgz"
  delegate_to: localhost
  become: no

- name: Extract backend components to target
  unarchive:
    src: "../backend.tgz"
    dest: "{{ reternal.install_dir }}"

- name: Build backend/api container
  docker_image:
    name: reternal/backend
    path: "{{ backend_target_dir }}"
    force: yes

- name: Run backend container
  docker_container:
    name: reternal-backend
    image: reternal/backend
    state: started
    recreate: yes
    env:
      JWT_SECRET: "{{ passwords.jwt_secret }}"
      FLASK_SECRET: "{{ passwords.api_secret }}"
      CORS_DOMAIN: "{{ reternal.cors }}"
      C2_DEST: "{{ reternal.c2_dest }}"
      MONGO_PASSWORD: "{{ passwords.mongo_reternal_pass }}"
    networks:
      - name: backend_network
        aliases:
          - reternal-backend
 
- name: Run backend SocketIO container
  docker_container:
    name: reternal-socketio
    image: reternal/backend
    state: started
    recreate: yes
    env:
      JWT_SECRET: "{{ passwords.mongo_root_user }}"
      FLASK_SECRET: "{{ passwords.mongo_root_user }}"
    networks:
      - name: backend_network
        aliases:
          - reternal-backend
    command: ['celery', '-A', 'app.tasks.listener.celery', 'worker', '-Q', 'api']
    