
- include_vars: vault.yml

- name: Importing default agent commands
  expect: 
    command: "python3 {{ reternal.install_dir }}/manage.py -a create -t command"
    responses:
      (.*)Mongo Password(.*): "{{ passwords.mongo_reternal_pass }}"
  register: manage_script

- debug: msg="{{ manage_script.stdout }}"
