- hosts: all
  tags: ['all', 'core']
  become: yes
  strategy: free
  roles:
    - role: generic
      tags: ['generic']

    - role: firewall
      tags: ['firewall']

    - role: docker
      tags: ['docker']


- hosts: backend
  tags: ['backend', 'reternal']
  become: yes
  roles:
    - role: mongodb
      tags: ['mongodb']
    - role: redis
      tags: ['redis']
    - role: api
      tags: ['api']


- hosts: frontend
  tags: ['frontend', 'reternal']
  become: yes
  roles:
    - role: ui
      tags: ['ui']


- hosts: c2
  tags: ['c2', 'reternal']
  become: yes
  roles:
    - role: c2
      tags: ['c2']


- hosts: compilers
  tags: ['compilers', 'reternal']
  become: yes
  roles:
    - role: compiler
      tags: ['compiler']


- hosts: proxies
  tags: ['proxies']
  become: yes
  roles:
    - role: certs
      tags: ['certs']
    - role: proxy
      tags: ['proxy'] 


- hosts: backend
  tags: ['backend', 'utils']
  become: yes
  vars_prompt:
    - name: "login_username"
      prompt: "Username for Reternal auth"
      private: no
    - name: "login_password"
      prompt: "Password for Reternal auth"
      private: yes
  roles:
    - role: management
      tags: ['management']
    - role: usercreate
      tags: ['usercreate']
    - role: attck
      tags: ['attck']
    - role: mapping
      tags: ['mapping']
    - role: commands
      tags: ['commands']