- hosts: all
  become: yes
  strategy: free
  roles:
    - role: generic
      tags: ['generic', 'core']

    - role: firewall
      tags: ['firewall', 'core']

    - role: docker
      tags: ['docker', 'core']

    