- hosts: all
  become: yes
  strategy: free
  roles:
    - role: generic
      tags: ['generic', 'core']

    - role: firewall
      tags: ['firewall', 'core']

    - role: docker
      tags: ['docker', 'core']

- hosts: backend
  become: yes
  roles:
    - role: backend
      tags: ['backend', 'reternal']

- hosts: ui
  become: yes
  roles:
    - role: ui
      tags: ['ui', 'reternal']

- hosts: c2
  become: yes
  roles:
    - role: c2
      tags: ['c2', 'reternal']
      
- hosts: compiler
  become: yes
  roles:
    - role: compiler
      tags: ['compiler', 'reternal']

- hosts: proxy
  become: yes
  roles:
    - role: certs
      tags: ['certs', 'reternal']
    - role: proxy
      tags: ['proxy', 'reternal']