- hosts: all
  become: yes
  strategy: free
  roles:
    - role: generic
      tags: ['generic', 'core']

    - role: firewall
      tags: ['firewall', 'core']

    - role: docker
      tags: ['docker', 'core']


- hosts: backend
  become: yes
  roles:
    - role: backend
      tags: ['backend', 'reternal']


- hosts: ui
  become: yes
  roles:
    - role: ui
      tags: ['ui', 'reternal']
      


    