- hosts: all
  gather_facts: yes

- hosts: all
  tags: ['all', 'core']
  roles:
    - role: docker
      tags: ['docker']

- hosts: standalone
  gather_facts: yes
  tags: ['standalone', 'reternal']
  roles:
    - role: ca
      tags: ['ca', 'custom', 'utils']
    - role: mongodb
      tags: ['mongodb', 'default', 'container']
    - role: redis
      tags: ['redis', 'default', 'container']
    - role: rabbitmq
      tags: ['rabbitmq', 'default', 'container']
    - role: empire2
      tags: ['empire2', 'default', 'container']
    - role: c2
      tags: ['c2', 'custom', 'container']
    - role: search
      tags: ['search', 'custom', 'container']
    - role: api
      tags: ['api', 'custom', 'container']
    - role: empire2bit
      tags: ['empire2bit', 'custom', 'container']
    - role: frontend
      tags: ['frontend', 'custom', 'container']
    - role: proxy
      tags: ['proxy', 'custom', 'container']
    - role: apitasks
      tags: ['apitasks', 'custom', 'container']

- hosts: victims
  gather_facts: yes
  tags: ['victim', 'reternal']
  roles:
    - role: victim
      tags: ['victim', 'custom', 'container']