- name: Run API container
  docker_container:
    name: api
    image: "reternal/backend:{{ api.tag }}"
    state: started
    purge_networks: yes
    networks_cli_compatible: yes
    pull: "{{ api.pull | default('yes') }}"
    recreate: "{{ api.recreate | default('yes') }}"
    env:
      RT_CELERY_BACKEND: "{{ celery.backend }}"
      RT_CELERY_BROKER: "{{ celery.broker }}"
    networks:
      - name: backend_network
        aliases:
          - api