- name: Build API image
  docker_image:
    build: 
      path: "{{ api.build_path }}"
    force: "{{ api.recreate | default('yes') }}"
    name: reternal-dev/api
    tag: latest
    source: build

- name: Run API container
  docker_container:
    name: api
    image: "reternal-dev/api:latest"
    state: started
    purge_networks: yes
    networks_cli_compatible: yes
    recreate: "{{ api.recreate | default('yes') }}"
    volumes:
      - "{{ api.build_path }}/app:/home/reternal/app"
    env:
      RT_CELERY_BACKEND: "{{ celery.backend }}"
      RT_MONGO_HOST: "mongodb"
      RT_REDIS_PATH_SOCKETIO: "{{ redis.path.socketio }}"
      RT_CELERY_BROKER: "{{ celery.broker }}"
      RT_REDIS_PATH_CACHE: "{{ redis.path.cache }}"
      RT_MONGO_USERNAME: "{{ mongodb.username }}"
      RT_MONGO_PASSWORD: "{{ vault.mongodb.password }}"
      RT_CORS_ALLOW_ORIGIN: "{{ api.cors }}"
      RT_SERVICE_TOKEN: "{{ vault.api.service_token }}"
      RT_OAUTH2_ISSUER: "{{ openid.issuer_url }}"
      RT_OAUTH2_AUDIENCE: "{{ openid.audience }}"
      RT_OAUTH2_OPENID_CONFIG: "{{ openid.config_url }}"
      RT_C2_ENABLED: "{{ c2.enabled }}"
      RT_SEARCH_ENABLED: "{{ search.enabled }}"
      FASTAPI_DEBUG: "True"
    ports:
      - "127.0.0.1:5000:5000"
    
    networks:
      - name: backend_network
        aliases:
          - api