- include_vars: vault.yml

- name: Making sure default install directory is created
  file:
    path: "{{ reternal.install_dir }}"
    state: directory

- name: Run API container
  docker_container:
    name: api
    image: "reternal/backend:{{ api.tag }}"
    state: started
    purge_networks: yes
    networks_cli_compatible: yes
    pull: "{{ api.pull | default('yes') }}"
    recreate: "{{ api.recreate | default('yes') }}"
    env:
      RT_CELERY_BACKEND: "{{ celery.backend }}"
      RT_CELERY_BROKER: "{{ celery.broker }}"
    networks:
      - name: backend_network
        aliases:
          - api
 
# - name: Run backend SocketIO container
#   docker_container:
#     name: reternal-socketio
#     image: reternal/backend
#     state: started
#     recreate: yes
#     env:
#       JWT_SECRET: "{{ passwords.jwt_secret }}"
#       FLASK_SECRET: "{{ passwords.api_secret }}"
#       MONGO_PASSWORD: "{{ passwords.mongo_reternal_pass }}"
#     networks:
#       - name: backend_network
#         aliases:
#           - reternal-backendsocket
#     command: ['celery', '-A', 'app.tasks.listener.celery', 'worker', '-Q', 'api']
    